# -*- coding: utf-8 -*-
"""Boston housing.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FpxondbqhsrkjtkMC5PinrLqnoKBXDqy
"""

import numpy as np
import matplotlib.pyplot as plt 

import pandas as pd  
import seaborn as sns

from sklearn.datasets import load_boston
boston_dataset = load_boston()

df = pd.DataFrame(boston_dataset.data, columns=boston_dataset.feature_names)
df

df.head()

df['MEDV'] = boston_dataset.target

df.isnull().sum()

sns.set(rc={'figure.figsize':(11.7,8.27)})
sns.distplot(df['MEDV'], bins=30)
plt.show()

df

X=df.iloc[:,0:-1]
X
y=df.iloc[:,-1]
y

from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state=5)

from sklearn.preprocessing import MinMaxScaler
scaler = MinMaxScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

plt.semilogy()

from sklearn.linear_model import SGDRegressor

sgd_reg = SGDRegressor()
sgd_reg.fit(X_train, Y_train)
sgd_reg.score(X_train,y_train)

sgd_reg.score(X_test,y_test)

from sklearn.metrics import r2_score

y_pred = sgd_reg.predict(X_test) #r2 score
r2_score(y_test, y_pred)

from sklearn.metrics import median_absolute_error

y_pred = sgd_reg.predict(X_test)
median_absolute_error(y_test,y_pred)